export const phrases = [
  "Quiero ser recordado como parte del grupo de los mejores jugadores.",
  "Tu amor me hace fuerte, tu odio me hace imparable.",
  "Quiero jugar siempre bien y ganar títulos. Solo estoy en el comienzo.",
  "Quizás me odian porque soy muy bueno.",
  "La experiencia te hace entender que jugando en equipo y siendo solidario se alcanzan mayores objetivos.",
  "Mi fuerza mental es muy importante para mí.",
  "Estoy viviendo un sueño del que nunca me quiero levantar.",
  "No hay nada malo en soñar en ser el mejor jugador del mundo. Se trata de intentar ser el mejor. Seguiré trabajando duro para conseguirlo, está dentro de mis posibilidades.",
  "Algunos fans me abuchean y silban porque soy guapo, rico y buen jugador. Me envidian.",
  "Aún recuerdo cuando mi maestra me decía que el fútbol no daba de comer.",
  "No quiero ser comparado con nadie, me gustaría imponer mi propio estilo de juego y hacer lo mejor para mí y para el club.",
  "Sin fútbol, mi vida no valdría nada.",
  "Cada temporada es un nuevo desafío para mí, y siempre me propongo mejorar en términos de partidos, goles y asistencias.",
  "No soy un perfeccionista, pero me gusta sentir que las cosas se hacen bien. Más que eso, siento una necesidad interminable de aprender, de mejorar, de involucrarme, no solo para agradar al entrenador y a los aficionados, sino para sentirme satisfecho conmigo mismo.",
  "Estaré muy orgulloso si un día tengo la misma estima que George Best o David Beckham. Es en lo que estoy trabajando.",
  "Yo sé que al que le gusta el fútbol, le gusto yo.",
  "Hoy hay oportunidades que nadie sabe si volverán a aparecer en el futuro.",
  "El talento no lo es todo. Lo puedes tener desde la cuna, pero es necesario aprender el oficio para ser el mejor.",
  "La gente tiene que entender una cosa: a los 18, llegué a un club de ensueño como el Manchester United. Era un sueño hecho realidad. Pero, incluso en ese momento, estaba pensando en jugar en Inglaterra algunos años y luego ir a jugar a España. Incluso en ese momento estaba pensando así, y siempre di el 100%.",
  "Estoy orgulloso de jugar para el Real Madrid porque me divierto; cuando no te diviertes es un signo de que es el momento para marcharse. Por ahora, estoy feliz aquí en el mayor club del mundo.",
  "Estoy muy feliz de firmar por el mejor club del mundo y especialmente orgulloso de ser el primer portugués de jugar para el United.",
  "Quiero ganar, independientemente de donde sea.",
  "Mi padre siempre estaba de buen humor, amaba el fútbol. Me entristece un poco porque si pudiera disfrutar de verme ahora, lo que he logrado, eso sería lo mejor de su vida. Pero estoy seguro de que él me cuida desde arriba.",
  "Cuando pierdes a alguien que amas tanto, sobrevivir a la pérdida es difícil.",
  "También tengo mis defectos, pero soy un profesional al que no le gusta perder o fallar.",
  "Prácticamente no tengo vida privada. Ya estoy acostumbrado a ello. Si, a veces es duro, pero es la elección que tomé.",
  "Es obvio que molesta a la gente cuando gana el Real Madrid. Les pone celosos. No hay igualdad de condiciones.",
  "Si Dios no agrada a todos, no les voy a agradar yo.",
  "¿Por qué mentir? No voy a ser un hipócrita y decir lo opuesto a lo que pienso, como hacen otros.",
  "Aún aprendo, pero creo que es lo mejor de la vida tener un hijo.",
  "Soy consciente de que sean cuales sean las circunstancias, siempre habrá especulaciones sobre mí.",
  "Nunca prometo nada. No prometo nada a mi madre. No prometo nada a los aficionados.",
  "Demasiada humildad es un defecto.",
  "Para mí, ser el mejor significa probarlo en diferentes países y campeonatos.",
  "Sé que si marco, ganaremos el partido.",
  "Es mi convicción que no hay límites para aprender.",
  "Muchos jugadores jóvenes han triunfado en el United. ¿Por qué no me puede ocurrir a mí? No estoy preocupado por ser joven. Es un incentivo para hacerlo lo mejor que pueda.",
  "Me motiva mucho que la gente se interese por mí.",
  "No tengo que demostrar nada a nadie. No hay nada que demostrar.",
  "Lo que hago como jugador individual solo es importante si ayuda al equipo a ganar. Eso es lo más importante.",
  "El punto más alto de mi carrera fue ganar la Liga de Campeones. Nadie lo borrará jamás de mi memoria, de la misma forma que nadie borrará el hecho de que lo hice con la camiseta del Manchester United.",
  "El número 7 es un honor y una responsabilidad. Espero que me traiga mucha suerte.",
  "Dios nunca duerme, sabe quién se lo merece.",
  "Marcar goles es una gran sensación, pero lo más importante para mí es que el equipo sea exitoso, no importa quién meta los goles mientras ganemos.",
  "No tiene sentido hacer predicciones. No merece la pena especular porque nada está escrito en la piedra y las cosas cambian todo el tiempo en el fútbol.",
  "Sé que soy un buen profesional, sé que nadie es tan duro conmigo como yo mismo y eso nunca va a cambiar.",
  "No estoy preocupado por el Balón de Oro. No me quita el sueño, pero no voy a ser hipócrita, claro que me gustaría ganarlo.",
  "Estoy muy contento con mi vida y con mi personalidad. No voy a cambiar nada.",
  "Cuando gano premios, pienso en mi padre.",
  "Nunca he escondido el hecho de que es mi intención ser el mejor.",
];

export const information = [
  "Cristiano Ronaldo nació el 5 de febrero de 1985 en Funchal, Madeira, Portugal.",
  "Su nombre completo es Cristiano Ronaldo dos Santos Aveiro.",
  "Es considerado uno de los mejores futbolistas de todos los tiempos.",
  "Ha ganado el premio Balón de Oro en cinco ocasiones.",
  "Cristiano Ronaldo comenzó su carrera profesional en el Sporting de Lisboa.",
  "En 2003, fichó por el Manchester United, donde se consagró como una estrella mundial.",
  "En 2009, fue traspasado al Real Madrid por una cifra récord en ese momento.",
  "Con el Real Madrid, Ronaldo ganó cuatro Champions League y se convirtió en el máximo goleador de la historia del club.",
  "En 2018, se unió a la Juventus, equipo en el que actualmente juega.",
  "Es el máximo goleador de la selección portuguesa y ha representado a su país en varias competiciones internacionales.",
  "Ronaldo ha anotado más de 700 goles a lo largo de su carrera profesional.",
  "Es conocido por su dedicación y trabajo duro en el entrenamiento, lo cual le ha ayudado a mantenerse en la cima durante muchos años.",
  "Tiene una gran rivalidad deportiva con el futbolista argentino Lionel Messi, considerados dos de los mejores jugadores de la historia.",
  "Es uno de los atletas mejor pagados del mundo y ha obtenido numerosos contratos publicitarios con marcas reconocidas.",
  "Además del fútbol, Cristiano Ronaldo es conocido por su generosidad y apoyo a diversas causas benéficas.",
  "Es un gran aficionado al fitness y cuida mucho su físico.",
  "Cristiano Ronaldo es padre de cuatro hijos: Cristiano Jr., los mellizos Eva y Mateo, y Alana Martina.",
  "Tiene su propia marca de ropa y fragancias llamada CR7.",
  "Es el primer futbolista en alcanzar los 100 goles en competiciones europeas de clubes.",
  "Ha ganado múltiples títulos de liga y copas nacionales en las ligas en las que ha jugado.",
  "Cristiano Ronaldo es reconocido por su velocidad, potencia física y habilidades técnicas, lo que le ha permitido destacar en diferentes equipos y ligas a lo largo de su carrera.",
];

import cr7_1 from "../assets/images/ronaldo/cr7-1.png";
import cr7_2 from "../assets/images/ronaldo/cr7-3.png";
import cr7_3 from "../assets/images/ronaldo/cr7-7.png";
import cr7_4 from "../assets/images/ronaldo/cr7-4.png";
import cr7_5 from "../assets/images/ronaldo/cr7-8.png";
import cr7_6 from "../assets/images/ronaldo/cr7-6.png";

export const images = [cr7_1, cr7_2, cr7_3, cr7_4, cr7_5, cr7_6];
